### ISSUE TITLE
Ajout des pays dans Contact.html

### ISSUE THREAD

**Issue by aslen77** [aslen77/GarfieldIce#5]
Ajouter tous les autres pays dans le select 
` <select name="pays" id="storyS">
                   <option value="0" disabled selected>Select</option>
                   <option value="France">France</option>
                   <option value="Tunisie">Tunisie</option>
                   <option value="Allemagne">Allemagne</option>
                   <option value="Romanie">Romanie</option>
               </select>`

**Comment by Chayma27** [comment]
J Peut Pas L Faire Taoua PasQ Naarafech Naamal Pull L Dossier Teek L'étape Heky Mezelet Ma Aalamet'helich

**Comment by aslen77** [comment]
ah d'accord okei
