### ISSUE TITLE
Prblm Niveau De Header

### ISSUE THREAD

**Issue by Chayma27** [aslen77/GarfieldIce#6]
Au Niveau du header "Articles" est toujours en noirs alors que nrmlmnt Yelzem Tebda En Noir Ken Kif Nenzel Aaliha Oo Nhelha
Mais Même Si Nenzel Expl Aala "Contact" Oo Nhel Contact Dima "Articles" To9eed En Noir Lin Nchok N9oul Yekhy Hala "Contact" Ouala "Articles" !

**Comment by aslen77** [comment]
Bon a la base ena 3ammelha akkeka apres si tu veux je le change c'est vrai
